import type { CatalogItem, SlotDefinition } from '@/types/catalog';

export const SLOTS: SlotDefinition[] = [
  {
    category: 'table',
    label: 'Desk',
    maxItems: 1,
    description: 'Select your primary workspace desk',
  },
  {
    category: 'chair',
    label: 'Chair',
    maxItems: 1,
    description: 'Choose a comfortable chair',
  },
  {
    category: 'monitor',
    label: 'Monitors',
    maxItems: 3,
    description: 'Up to 3 monitors on a monitor arm',
  },
  {
    category: 'decorative',
    label: 'Decor',
    maxItems: 10,
    description: 'Desk lamp, plants, and accessories',
  },
  {
    category: 'shelf',
    label: 'Shelf',
    maxItems: 1,
    description: 'Bookshelf or wall-mounted storage',
  },
];

export const CATALOG_ITEMS: CatalogItem[] = [
  {
    id: 'computer_desk',
    name: 'Computer Desk',
    category: 'table',
    price: 29900,
    modelUrl: '/models/computer_desk.glb',
    scale: 0.8,
    slotPosition: [0, 0.4, 0],
    rotation: [0, 0, 0],
    description: 'Standard computer desk with cable management',
  },
  {
    id: 'wood_desk',
    name: 'Wooden Desk',
    category: 'table',
    price: 39900,
    modelUrl: '/models/wooden_desk.glb',
    scale: 0.7,
    slotPosition: [0, 0.44, 0],
    rotation: [0, 0, 0],
    description: 'Warm wood finish traditional desk',
  },
  {
    id: 'gaming_chair',
    name: 'Gaming Chair',
    category: 'chair',
    price: 39900,
    modelUrl: '/models/gaming_chair.glb',
    scale: 0.03,
    slotPosition: [-0.47, -0.78, -0.02],
    rotation: [0, -2.74, 0],
    description: 'Ergonomic gaming chair with lumbar support',
  },
  {
    id: 'office_chair',
    name: 'Office Chair',
    category: 'chair',
    price: 34900,
    modelUrl: '/models/office_chair.glb',
    scale: 0.815,
    slotPosition: [0.13, 0.6, 0.64],
    rotation: [0, -2.58, 0],
    description: 'Professional office chair with armrests',
  },
  {
    id: 'plastic_chair',
    name: 'Garden Chair',
    category: 'chair',
    price: 9900,
    modelUrl: '/models/plastic_chair.glb',
    scale: 0.74,
    slotPosition: [-0.03, 0.56, 0.62],
    rotation: [0, 3.11, 0],
    description: 'Simple plastic garden or cafe chair',
  },
  {
    id: 'monitor',
    name: 'Standard Monitor',
    category: 'monitor',
    price: 19900,
    modelUrl: '/models/monitor.glb',
    scale: 0.00028,
    slotPosition: [-1574.86, -84.52, -101.57],
    rotation: [0, -0.4, 0],
    description: '24-inch standard monitor',
  },
  {
    id: 'curved_monitor',
    name: 'Curved Monitor',
    category: 'monitor',
    price: 34900,
    modelUrl: '/models/curved_monitor.glb',
    scale: 0.00028,
    slotPosition: [-1574.86, -84.52, -101.57],
    rotation: [0, -0.4, 0],
    description: '27-inch curved gaming monitor',
  },
  {
    id: 'ultrawide_monitor',
    name: 'Ultrawide Monitor',
    category: 'monitor',
    price: 59900,
    modelUrl: '/models/ultrawide_monitor.glb',
    scale: 0.00028,
    slotPosition: [-1574.86, -84.52, -101.57],
    rotation: [0, -0.4, 0],
    description: '34-inch ultrawide monitor',
  },
  {
    id: 'desk_lamp',
    name: 'Desk Lamp',
    category: 'decorative',
    price: 4900,
    modelUrl: '/models/desk_lamp.glb',
    scale: 0.12,
    slotPosition: [-0.8, 1.91, -0.2],
    rotation: [0, 0, 0],
    description: 'Adjustable LED desk lamp',
  },
  {
    id: 'sci-fi_desk_lamp',
    name: 'Sci-Fi Desk Lamp',
    category: 'decorative',
    price: 7900,
    modelUrl: '/models/sci-fi_desk_lamp.glb',
    scale: 0.12,
    slotPosition: [-0.8, 1.91, -0.2],
    rotation: [0, 0, 0],
    description: 'Futuristic desk lamp with RGB accent',
  },
  {
    id: 'fake_plant',
    name: 'Fake Plant',
    category: 'decorative',
    price: 2900,
    modelUrl: '/models/fake_plant.glb',
    scale: 0.12,
    slotPosition: [-0.8, 1.91, -0.2],
    rotation: [0, 0, 0],
    description: 'Low-maintenance decorative plant',
  },
  {
    id: 'pencil_holder',
    name: 'Pencil Holder',
    category: 'decorative',
    price: 1900,
    modelUrl: '/models/pencil_holder.glb',
    scale: 0.12,
    slotPosition: [-0.8, 1.91, -0.2],
    rotation: [0, 0, 0],
    description: 'Desk organizer for pens and supplies',
  },
  {
    id: 'modern_bookshelf',
    name: 'Modern Bookshelf',
    category: 'shelf',
    price: 24900,
    modelUrl: '/models/modern_bookshelf.glb',
    scale: 0.12,
    slotPosition: [-0.8, 1.91, -0.2],
    rotation: [0, 0, 0],
    description: 'Contemporary bookshelf with open shelving',
  },
  {
    id: 'wooden_bookshelf',
    name: 'Wooden Bookshelf',
    category: 'shelf',
    price: 29900,
    modelUrl: '/models/wooden_bookshelf.glb',
    scale: 0.12,
    slotPosition: [-0.8, 1.91, -0.2],
    rotation: [0, 0, 0],
    description: 'Classic wooden bookshelf with multiple tiers',
  },
  {
    id: 'mounted_bookshelf',
    name: 'Wall-Mounted Shelf',
    category: 'shelf',
    price: 14900,
    modelUrl: '/models/mounted_bookshelf.glb',
    scale: 0.12,
    slotPosition: [-0.8, 1.91, -0.2],
    rotation: [0, 0, 0],
    description: 'Space-saving wall-mounted shelf unit',
  },
];

export function getItemsByCategory(category: CatalogItem['category']): CatalogItem[] {
  return CATALOG_ITEMS.filter((item) => item.category === category);
}

export function formatPrice(cents: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(cents / 100);
}